apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grav.fullname" . }}
  labels: {{- include "grav.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gravPassword }}
  grav-password: {{ .Values.gravPassword | b64enc | quote }}
  {{- else }}
  grav-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.smtpPassword }}
  smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
  {{- end }}
